name: docentral
description:
  "DocCentral is a cross-platform Flutter application designed to help doctors and their assistants efficiently manage appointments, patients, payments, and inventory.
  Built with Firebase integration and modern state management, it aims to streamline medical practice workflows with a clean, user-friendly interface."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: any
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  go_router: ^15.2.4
  google_fonts: ^6.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
