// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-icnDL8kPDgI8S36lqQL9uxTN11UotI',
    appId: '1:548367256785:web:b46489b8727a4d5837c9f0',
    messagingSenderId: '548367256785',
    projectId: 'doccentral-c473b',
    authDomain: 'doccentral-c473b.firebaseapp.com',
    storageBucket: 'doccentral-c473b.firebasestorage.app',
    measurementId: 'G-FBLNXFMRET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AN7NOjJm8Yp6vS7y-l1QkGanQ47cfDs',
    appId: '1:548367256785:android:aca276e16751601c37c9f0',
    messagingSenderId: '548367256785',
    projectId: 'doccentral-c473b',
    storageBucket: 'doccentral-c473b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6o28zhrbAXg9aRx2M03RojLETwtK79f4',
    appId: '1:548367256785:ios:201e5a2e0f5ce5a837c9f0',
    messagingSenderId: '548367256785',
    projectId: 'doccentral-c473b',
    storageBucket: 'doccentral-c473b.firebasestorage.app',
    iosBundleId: 'com.codenest.docentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6o28zhrbAXg9aRx2M03RojLETwtK79f4',
    appId: '1:548367256785:ios:201e5a2e0f5ce5a837c9f0',
    messagingSenderId: '548367256785',
    projectId: 'doccentral-c473b',
    storageBucket: 'doccentral-c473b.firebasestorage.app',
    iosBundleId: 'com.codenest.docentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2-icnDL8kPDgI8S36lqQL9uxTN11UotI',
    appId: '1:548367256785:web:c6078148992b926837c9f0',
    messagingSenderId: '548367256785',
    projectId: 'doccentral-c473b',
    authDomain: 'doccentral-c473b.firebaseapp.com',
    storageBucket: 'doccentral-c473b.firebasestorage.app',
    measurementId: 'G-0FJFZ74JVS',
  );
}
